import { createHash } from 'node:crypto'
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { format } from 'prettier'

// Constants -------------------------------------------------------------------
const root = join(import.meta.dir, '..')
const output = join(root, 'src/generated/migrations.ts')
const journal = JSON.parse(readFileSync(join(root, 'drizzle/meta/_journal.json'), 'utf8')) as {
  entries: { idx: number; tag: string }[]
}

// API -------------------------------------------------------------------------
const migrations = journal.entries.map(({ idx, tag }, position) => {
  if (idx !== position || !/^\d{4}_[a-z0-9_-]+$/.test(tag)) {
    throw new Error(`Invalid or unordered migration: ${tag}`)
  }
  const sql = readFileSync(join(root, 'drizzle', `${tag}.sql`), 'utf8')
  const statements = sql
    .split(/--> statement-breakpoint\s*/g)
    .map((statement) => statement.trim())
    .filter(Boolean)
  if (!statements.length) throw new Error(`Empty migration: ${tag}`)
  return {
    tag,
    hash: createHash('sha256').update(sql).digest('hex'),
    statements,
  }
})
const source = await format(
  `// Generated by scripts/embed-migrations.ts; do not edit.\nexport const migrations = ${JSON.stringify(migrations, null, 2)} as const\n`,
  { parser: 'typescript', semi: false, singleQuote: true, printWidth: 100, trailingComma: 'all' },
)

if (process.argv.includes('--check')) {
  if (readFileSync(output, 'utf8') !== source) throw new Error('Embedded migrations are stale')
} else {
  mkdirSync(join(root, 'src/generated'), { recursive: true })
  writeFileSync(output, source)
}
